name: deploy website
on:
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: "main"
        required: true
  schedule:
    - cron: "*/30 * * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn
      - name: Recreate all posts
        shell: bash
        run: |
          npm install -g yarn
          yarn install --immutable
          yarn build --token=${{ secrets.VERCEL_TOKEN }}
          yarn dev --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Recreate all posts
      #   shell: bash
      #   run: |
      #     yarn install --immutable
      #     yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      #     yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      #     yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
